### PR TITLE
✨ Add side by side view

### PR DESCRIPTION
**Pull request by victorborrasdev**

### CODE REVIEW

**Review by ricardoferrolho — APPROVED** [review]
There's a little minor thing but I don't think it's worth the effort: when we select a month in the "next" month, it is selected as the current month.

**Comment by victorborrasdev** [comment]
> There's a little minor thing but I don't think it's worth the effort: when we select a month in the "next" month, it is selected as the current month.

I don't think I get it, it looks fine for me 🤔  
imagen

**Comment by ricardoferrolho** [comment]
> > There's a little minor thing but I don't think it's worth the effort: when we select a month in the "next" month, it is selected as the current month.
> 
> I don't think I get it, it looks fine for me thinking imagen

If you click to select a different month on the right side (Oct 2021 in this case) and select another month, that selected month will be in the left side (as the selected month becomes the actual month) and not on the right (as the next month). But again, don't worry about it.

**Comment by victorborrasdev** [comment]
oh, I see, so if you click on Oct 2021 and select December for insance, you'd expect it to appear on the right side, right? Then november on the left? Makes sense, we can add that in the future

**Pull request merged**
